"""Thin HTTP client for the existing FastAPI backend. It contains NO model logic.

SAMPLE_PAYLOADS holds a valid, REAL request body for each /predict/* endpoint --
never invented values. CWRU's sample comes from tests/test_cwru.py (the same
one already validated as a regression check). C-MAPSS and IMS still need their
real sample files (tools/sample_payloads/cmapss_payload_real.json and
ims_payload_real_*.json, generated by tools/generate_real_test_payloads.py) --
until those are supplied, those two stay disconnected honestly rather than
being filled with made-up feature vectors or signal data.

RESPONSE_TRANSFORMS replaces the old flat FIELD_MAP dotted-path lookup, because
the real responses aren't flat:
  - /predict/cwru returns `probabilities` as a dict keyed by class name, not a
    single `confidence` number -- the transform picks out the probability of
    the predicted class specifically.
  - /predict/ims returns `results` as an array (one entry per channel), not a
    single score -- the transform reports the most anomalous channel, since
    that's the one that should drive a machine-status dashboard.
  - /predict/cmapss is already flat (`predicted_rul`), so its transform is a
    trivial rename.

To (re)inspect the real schemas at any time:

    python frontend/api_client.py http://localhost:8000
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Callable

import pandas as pd
import requests

SAMPLE_PAYLOADS_DIR = Path(__file__).resolve().parent / "sample_payloads"


def _load_real_payload(filename: str) -> dict | None:
    """Load a real sample payload bundled alongside this file. Returns None
    (never invented data) if the file isn't present, so the dashboard falls
    back to an honest 'not connected' state instead of fabricating values."""
    path = SAMPLE_PAYLOADS_DIR / filename
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)

DEFAULT_BASE_URL = os.getenv("FASTAPI_BASE_URL", "http://localhost:8000")
TIMEOUT_S = 5

ENDPOINTS = {
    "health": "/health",
    "cwru": "/predict/cwru",
    "ims": "/predict/ims",
    "cmapss": "/predict/cmapss",
    "sensor": "/sensor-data",
}

# --- Real sample payloads -----------------------------------------------------------
# CWRU: from tests/test_cwru.py's REAL_CWRU_SAMPLE (previously validated to
# predict "Ball" -- a genuine regression-tested sample, not invented).
CWRU_REAL_SAMPLE = {
    "rms": 0.1337138105163796,
    "kurtosis": -0.1007173256513138,
    "skewness": 0.0118660165725503,
    "peak_to_peak": 0.9344893013972057,
    "std": 0.1336768542272595,
    "dominant_freq": 13476.5625,
    "spectral_energy": 0.0089446315778231,
    "spectral_centroid": 10739.134218762923,
    "energy_0_1000": 0.00007277456347761555,
    "energy_1000_2500": 0.000300211021384,
    "energy_2500_5000": 0.0003055405350038,
    "load": 0,
}

# IMS and C-MAPSS: real payloads generated by tools/generate_real_test_payloads.py
# (the same fixtures tests/conftest.py uses), bundled here as JSON so the
# dashboard doesn't depend on the backend project's file layout. If a file is
# missing, _load_real_payload returns None and that model honestly shows
# "not connected" rather than being fed made-up data.
SAMPLE_PAYLOADS: dict[str, dict | None] = {
    "cwru": CWRU_REAL_SAMPLE,
    "ims": _load_real_payload("ims_payload_real_2nd_test_latest.json"),
    "cmapss": _load_real_payload("cmapss_payload_real.json"),
}


# --- Response shape transforms (replaces flat dotted-path FIELD_MAP) ----------------
def _transform_cwru(resp: dict) -> dict:
    predicted = resp["predicted_class"]
    probabilities = resp.get("probabilities") or {}
    return {
        "fault_class": predicted,
        "confidence": probabilities.get(predicted),
    }


def _transform_ims(resp: dict) -> dict:
    results = resp.get("results") or []
    if not results:
        raise ValueError("IMS response had an empty 'results' array.")
    # Report the most anomalous channel -- the one that should drive a
    # machine-status dashboard, rather than an arbitrary first entry.
    worst = max(results, key=lambda r: r["anomaly_score"])
    return {
        "score": worst["anomaly_score"],
        "threshold": None,  # not returned by this endpoint; the Isolation
                            # Forest's decision boundary is internal to the
                            # model, so no numeric threshold is available to
                            # display. is_anomaly below is authoritative.
        "is_anomaly": worst["is_anomaly"],
    }


def _transform_cmapss(resp: dict) -> dict:
    return {"rul": resp["predicted_rul"]}


RESPONSE_TRANSFORMS: dict[str, Callable[[dict], dict]] = {
    "cwru": _transform_cwru,
    "ims": _transform_ims,
    "cmapss": _transform_cmapss,
}

OPTIONAL_FIELDS = {"threshold"}
# -----------------------------------------------------------------------------------


class BackendError(Exception):
    """Raised for any connection, HTTP or decoding problem."""


def _url(base_url: str, path: str) -> str:
    return base_url.rstrip("/") + path


def _request(method: str, base_url: str, path: str, json: dict | None = None):
    try:
        resp = requests.request(method, _url(base_url, path), json=json, timeout=TIMEOUT_S)
        resp.raise_for_status()
        return resp.json()
    except requests.exceptions.ConnectionError:
        raise BackendError(f"Cannot reach {base_url}. Is the FastAPI container running?")
    except requests.exceptions.Timeout:
        raise BackendError(f"{base_url} did not answer within {TIMEOUT_S} s.")
    except requests.exceptions.HTTPError as e:
        raise BackendError(f"{path} returned HTTP {e.response.status_code}: {e.response.text[:200]}")
    except ValueError:
        raise BackendError(f"{path} did not return JSON.")


# --- One function per existing endpoint --------------------------------------------
def health_check(base_url: str = DEFAULT_BASE_URL) -> dict:
    return _request("GET", base_url, ENDPOINTS["health"])


def predict_cwru(payload: dict, base_url: str = DEFAULT_BASE_URL) -> dict:
    return _request("POST", base_url, ENDPOINTS["cwru"], json=payload)


def predict_ims(payload: dict, base_url: str = DEFAULT_BASE_URL) -> dict:
    return _request("POST", base_url, ENDPOINTS["ims"], json=payload)


def predict_cmapss(payload: dict, base_url: str = DEFAULT_BASE_URL) -> dict:
    return _request("POST", base_url, ENDPOINTS["cmapss"], json=payload)


def send_sensor_data(payload: dict, base_url: str = DEFAULT_BASE_URL) -> dict:
    """Submit an MPU6050 reading. Ingestion/diagnostic only, NOT an IMS prediction path."""
    return _request("POST", base_url, ENDPOINTS["sensor"], json=payload)


def get_latest_sensor(base_url: str = DEFAULT_BASE_URL) -> dict:
    """Fetch the backend's cached most-recent /sensor-data reading (display
    only -- see api/app.py's GET /sensor-data/latest)."""
    return _request("GET", base_url, "/sensor-data/latest")


def get_openapi_schema(base_url: str = DEFAULT_BASE_URL) -> dict:
    return _request("GET", base_url, "/openapi.json")


# --- Mapping backend responses to the dashboard --------------------------------------
def _run_model(name: str, predict_fn, base_url: str) -> dict:
    payload = SAMPLE_PAYLOADS[name]
    if payload is None:
        return {
            "available": False,
            "reason": f"No real sample payload supplied yet for '{name}'. "
                      f"Add it to SAMPLE_PAYLOADS in api_client.py once the "
                      f"real data file exists (see tools/sample_payloads/).",
        }
    try:
        resp = predict_fn(payload, base_url)
        values = RESPONSE_TRANSFORMS[name](resp)
    except BackendError as e:
        return {"available": False, "reason": str(e)}
    except (KeyError, TypeError, ValueError) as e:
        return {"available": False, "reason": f"Response from '{name}' did not match the expected shape: {e}"}
    return {"available": True, **values}


def _fetch_sensor_section(base_url: str) -> dict:
    """Build the dashboard's 'sensor' section from the live cache, matching
    mock_data's shape exactly so app.py's render_sensors() needs no changes."""
    try:
        resp = get_latest_sensor(base_url)
    except BackendError as e:
        return {
            "available": False, "latest": None,
            "history": pd.DataFrame(columns=["timestamp", "ax", "ay", "az", "rms"]),
            "note": str(e),
        }

    if not resp.get("available"):
        return {
            "available": False, "latest": None,
            "history": pd.DataFrame(columns=["timestamp", "ax", "ay", "az", "rms"]),
            "note": resp.get("reason", "No live sensor reading yet."),
        }

    latest_raw = resp["latest"]
    latest = {
        "ax": latest_raw["ax"], "ay": latest_raw["ay"], "az": latest_raw["az"],
        "rms": latest_raw["rms"],
        "sampling_rate_hz": latest_raw["sampling_rate_hz"],
        # The ESP32 sends a UTC timestamp (e.g. "...Z"), which pandas parses
        # as timezone-AWARE. utils.fmt_age() compares this against
        # datetime.now() (timezone-NAIVE), so the tz info must be dropped
        # here or the subtraction raises a TypeError. Only relative "N
        # seconds ago" display precision is needed, not real tz correctness.
        "timestamp": pd.to_datetime(latest_raw["timestamp"], utc=True).tz_localize(None).to_pydatetime(),
    }

    history = pd.DataFrame(resp.get("history") or [])
    if not history.empty:
        # Same tz-awareness fix as the single "latest" reading above.
        history["timestamp"] = pd.to_datetime(history["timestamp"], utc=True).dt.tz_localize(None)
        history = history[["timestamp", "ax", "ay", "az", "rms"]]
    else:
        history = pd.DataFrame(columns=["timestamp", "ax", "ay", "az", "rms"])

    return {"available": True, "latest": latest, "history": history, "note": None}


def get_backend_dashboard_data(base_url: str, machine_id: str) -> dict:
    """Same structure as mock_data.generate_mock_dashboard_data(), filled from FastAPI."""
    try:
        health = health_check(base_url)
        backend = ("Online", "GET /health answered")
        connection = ("Connected", base_url)
    except BackendError as e:
        health = None
        backend = ("Unreachable", str(e))
        connection = ("Disconnected", base_url)

    if health is not None:
        cwru = _run_model("cwru", predict_cwru, base_url)
        ims = _run_model("ims", predict_ims, base_url)
        cmapss = _run_model("cmapss", predict_cmapss, base_url)
        sensor = _fetch_sensor_section(base_url)
    else:
        off = {"available": False, "reason": "Backend unreachable."}
        cwru, ims, cmapss = dict(off), dict(off), dict(off)
        sensor = {
            "available": False, "latest": None,
            "history": pd.DataFrame(columns=["timestamp", "ax", "ay", "az", "rms"]),
            "note": "Backend unreachable.",
        }
    ims.setdefault("history", pd.DataFrame(columns=["timestamp", "score"]))
    cmapss.setdefault("history", pd.DataFrame(columns=["cycle", "rul"]))
    cmapss.setdefault("unit", "cycles")

    def state(r):
        return ("Result received", "Prediction endpoint answered") if r["available"] else ("Not connected", r["reason"])

    return {
        "mode": "backend",
        "is_mock": False,
        "machine_id": machine_id,
        "generated_at": datetime.now(),
        "sensor": sensor,
        "cwru": cwru, "ims": ims, "cmapss": cmapss,
        "system": {
            "backend": backend,
            "models": {"cwru": state(cwru), "ims": state(ims), "cmapss": state(cmapss)},
            "data_source": f"FastAPI backend at {base_url}",
            "connection": connection,
            "raw_health": health,
        },
    }


# --- CLI: print the real schemas so nothing has to be guessed -------------------------
def _fields(schema: dict, components: dict) -> dict:
    if "$ref" in schema:
        schema = components.get(schema["$ref"].split("/")[-1], {})
    return {k: v.get("type", v.get("$ref", "?").split("/")[-1]) for k, v in schema.get("properties", {}).items()}


def describe_backend(base_url: str) -> None:
    spec = get_openapi_schema(base_url)
    components = spec.get("components", {}).get("schemas", {})
    print(f"Routes exposed by {base_url}:\n")
    for path, methods in spec.get("paths", {}).items():
        for method, op in methods.items():
            body = op.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema")
            ok = op.get("responses", {}).get("200", {}).get("content", {}).get("application/json", {}).get("schema")
            print(f"{method.upper():5} {path}")
            if body:
                print("   request :", _fields(body, components) or body)
            if ok:
                print("   response:", _fields(ok, components) or ok)


if __name__ == "__main__":
    url = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_BASE_URL
    try:
        describe_backend(url)
    except BackendError as e:
        print("Error:", e)
