"""
tests/conftest.py
===================

Shared pytest fixtures:

  - client: a FastAPI TestClient wired through the app's own startup/
    shutdown lifespan, so the REAL production models load exactly once
    for the whole test session (via api/model_loader.py's
    load_all_models() -- no duplicated loading logic, no mocking, no
    retraining).

  - real_ims_payload / real_cmapss_payload: load the REAL sample request
    bodies generated by tools/generate_real_test_payloads.py (the same
    real data you already validated manually in Postman). If those files
    haven't been generated yet, the tests that need them are SKIPPED
    with a clear message -- never replaced with invented data.
"""

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from api.app import app

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SAMPLE_PAYLOADS_DIR = PROJECT_ROOT / "tools" / "sample_payloads"


@pytest.fixture(scope="session")
def client():
    """One shared TestClient for the whole test session.

    Using TestClient as a context manager ("with TestClient(app) as ...")
    is what actually triggers FastAPI's startup/shutdown lifespan --
    without it, load_all_models() would never run, and every /predict/*
    call would fail with "models not loaded".
    """
    with TestClient(app) as test_client:
        yield test_client


@pytest.fixture(scope="session")
def real_ims_payload() -> dict:
    """A real IMS request, generated from an actual raw snapshot file by
    tools/generate_real_test_payloads.py. Tries the 'earliest' file for
    2nd_test first, falls back to 'latest' -- either is fine, we just
    need one genuine real signal, not a specific one."""
    for filename in (
        "ims_payload_real_2nd_test_earliest.json",
        "ims_payload_real_2nd_test_latest.json",
    ):
        path = SAMPLE_PAYLOADS_DIR / filename
        if path.exists():
            with open(path) as f:
                return json.load(f)

    pytest.skip(
        f"No real IMS sample payload found in {SAMPLE_PAYLOADS_DIR}. "
        f"Run 'python tools/generate_real_test_payloads.py' first."
    )


@pytest.fixture(scope="session")
def real_cmapss_payload() -> dict:
    """A real C-MAPSS request (30 real engine cycles), generated from the
    actual engineered feature dataframe by
    tools/generate_real_test_payloads.py."""
    path = SAMPLE_PAYLOADS_DIR / "cmapss_payload_real.json"
    if not path.exists():
        pytest.skip(
            f"{path} not found. Run 'python tools/generate_real_test_payloads.py' first."
        )
    with open(path) as f:
        return json.load(f)
